channels:
  - defaults
dependencies:
  - ipython
  - ipywidgets
  - matplotlib
  - numpy
  - scipy==1.4.1
  - pandas
  - seaborn
  - nltk
  - gensim==3.8.1
  - beautifulsoup4==4.8.2
  - wikipedia==1.4.0
  - tomotopy==0.4.2
  - scikit-learn==0.22.1
  - spacy==2.1.3
  - bert-extractive-summarizer==0.3.0
  - wordcloud==1.6.0
  - tweepy==3.8.0
  - autocorrect
  - textblob
  - python-Levenshtein==0.12.0
  - keras==2.3.1